export const { Document } = jest.requireActual('../document')

export const documentExistsById = jest.fn()
export const updateDocument = jest.fn()
export const getDocumentsByIdsAndOwnerId = jest.fn()
export const createDocument = jest.fn()
export const countDocumentsByOwnerId = jest.fn()
export const getDocumentById = jest.fn()
export const getSingleDocumentById = jest.fn()
export const getDocumentsByOwnerId = jest.fn()
export const deleteDocument = jest.fn()
