/* eslint-disable @typescript-eslint/ban-types */
// tslint:disable
/**
 * Data Locker
 * This documents the API for the New America Data Locker project.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Agency
 */
export interface Agency {
  /**
   *
   * @type {string}
   * @memberof Agency
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Agency
   */
  name?: string
}
/**
 *
 * @export
 * @interface AgencyList
 */
export interface AgencyList {
  /**
   *
   * @type {Array<Agency>}
   * @memberof AgencyList
   */
  agencies?: Array<Agency>
}
/**
 *
 * @export
 * @interface Document
 */
export interface Document {
  /**
   *
   * @type {string}
   * @memberof Document
   */
  id?: string
  /**
   * Document description
   * @type {string}
   * @memberof Document
   */
  description?: string
  /**
   * File source
   * @type {string}
   * @memberof Document
   */
  source?: DocumentSourceEnum
  /**
   * File format
   * @type {string}
   * @memberof Document
   */
  format?: DocumentFormatEnum
  /**
   * Document Type
   * @type {string}
   * @memberof Document
   */
  type?: DocumentTypeEnum
  /**
   *
   * @type {string}
   * @memberof Document
   */
  expiryDate?: string
  /**
   *
   * @type {string}
   * @memberof Document
   */
  createdDate?: string
  /**
   *
   * @type {object}
   * @memberof Document
   */
  links?: object
}

/**
 * @export
 * @enum {string}
 */
export enum DocumentSourceEnum {
  PHOTO = 'PHOTO',
  SCAN = 'SCAN',
}
/**
 * @export
 * @enum {string}
 */
export enum DocumentFormatEnum {
  PNG = 'PNG',
  PDF = 'PDF',
  JPEG = 'JPEG',
}
/**
 * @export
 * @enum {string}
 */
export enum DocumentTypeEnum {
  SOCIALSECURITYCARD = 'SOCIAL_SECURITY_CARD',
  BIRTHCERTIFICATE = 'BIRTH_CERTIFICATE',
  PROOFOFINCOME = 'PROOF_OF_INCOME',
}

/**
 *
 * @export
 * @interface DocumentCreate
 */
export interface DocumentCreate {
  /**
   * Document description
   * @type {string}
   * @memberof DocumentCreate
   */
  description?: string
  /**
   * File format
   * @type {string}
   * @memberof DocumentCreate
   */
  format?: DocumentCreateFormatEnum
  /**
   * File source
   * @type {string}
   * @memberof DocumentCreate
   */
  source?: DocumentCreateSourceEnum
  /**
   * Document Type
   * @type {string}
   * @memberof DocumentCreate
   */
  type?: DocumentCreateTypeEnum
  /**
   *
   * @type {string}
   * @memberof DocumentCreate
   */
  expiryDate?: string
}

/**
 * @export
 * @enum {string}
 */
export enum DocumentCreateFormatEnum {
  PNG = 'PNG',
  PDF = 'PDF',
  JPEG = 'JPEG',
}
/**
 * @export
 * @enum {string}
 */
export enum DocumentCreateSourceEnum {
  PHOTO = 'PHOTO',
  SCAN = 'SCAN',
}
/**
 * @export
 * @enum {string}
 */
export enum DocumentCreateTypeEnum {
  SOCIALSECURITYCARD = 'SOCIAL_SECURITY_CARD',
  BIRTHCERTIFICATE = 'BIRTH_CERTIFICATE',
  PROOFOFINCOME = 'PROOF_OF_INCOME',
}

/**
 *
 * @export
 * @interface DocumentGrant
 */
export interface DocumentGrant {
  /**
   *
   * @type {string}
   * @memberof DocumentGrant
   */
  id?: string
  /**
   * Document Grant Type
   * @type {string}
   * @memberof DocumentGrant
   */
  type?: DocumentGrantTypeEnum
  /**
   *
   * @type {string}
   * @memberof DocumentGrant
   */
  createdDate?: string
  /**
   *
   * @type {DocumentGrantCreateAgencyDetails}
   * @memberof DocumentGrant
   */
  agencyDetails?: DocumentGrantCreateAgencyDetails
  /**
   *
   * @type {object}
   * @memberof DocumentGrant
   */
  links?: object
}

/**
 * @export
 * @enum {string}
 */
export enum DocumentGrantTypeEnum {
  AGENCYACCESS = 'AGENCY_ACCESS',
}

/**
 *
 * @export
 * @interface DocumentGrantCreate
 */
export interface DocumentGrantCreate {
  /**
   * Document Grant Type
   * @type {string}
   * @memberof DocumentGrantCreate
   */
  type?: DocumentGrantCreateTypeEnum
  /**
   *
   * @type {DocumentGrantCreateAgencyDetails}
   * @memberof DocumentGrantCreate
   */
  agencyDetails?: DocumentGrantCreateAgencyDetails
}

/**
 * @export
 * @enum {string}
 */
export enum DocumentGrantCreateTypeEnum {
  AGENCYACCESS = 'AGENCY_ACCESS',
}

/**
 *
 * @export
 * @interface DocumentGrantCreateAgencyDetails
 */
export interface DocumentGrantCreateAgencyDetails {
  /**
   * The ID of the agency
   * @type {string}
   * @memberof DocumentGrantCreateAgencyDetails
   */
  id?: string
}
/**
 *
 * @export
 * @interface DocumentGrantList
 */
export interface DocumentGrantList {
  /**
   *
   * @type {Array<DocumentGrant>}
   * @memberof DocumentGrantList
   */
  documents?: Array<DocumentGrant>
}
/**
 *
 * @export
 * @interface DocumentList
 */
export interface DocumentList {
  /**
   *
   * @type {Array<DocumentListItem>}
   * @memberof DocumentList
   */
  documents?: Array<DocumentListItem>
}
/**
 *
 * @export
 * @interface DocumentListItem
 */
export interface DocumentListItem {
  /**
   *
   * @type {string}
   * @memberof DocumentListItem
   */
  id?: string
  /**
   * Document Type
   * @type {string}
   * @memberof DocumentListItem
   */
  type?: DocumentListItemTypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum DocumentListItemTypeEnum {
  SOCIALSECURITYCARD = 'SOCIAL_SECURITY_CARD',
  BIRTHCERTIFICATE = 'BIRTH_CERTIFICATE',
  PROOFOFINCOME = 'PROOF_OF_INCOME',
}

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  givenName?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  familyName?: string
  /**
   *
   * @type {object}
   * @memberof User
   */
  links?: object
}
/**
 *
 * @export
 * @interface UserDelegatedAccess
 */
export interface UserDelegatedAccess {
  /**
   *
   * @type {string}
   * @memberof UserDelegatedAccess
   */
  email?: string
  /**
   *
   * @type {User}
   * @memberof UserDelegatedAccess
   */
  allowsAccessToUser?: User
  /**
   *
   * @type {string}
   * @memberof UserDelegatedAccess
   */
  createdDate?: string
  /**
   *
   * @type {object}
   * @memberof UserDelegatedAccess
   */
  links?: object
}
/**
 *
 * @export
 * @interface UserDelegatedAccessCreate
 */
export interface UserDelegatedAccessCreate {
  /**
   *
   * @type {string}
   * @memberof UserDelegatedAccessCreate
   */
  email?: string
}
/**
 *
 * @export
 * @interface UserDelegatedAccessList
 */
export interface UserDelegatedAccessList {
  /**
   *
   * @type {Array<UserDelegatedAccess>}
   * @memberof UserDelegatedAccessList
   */
  delegatedAccess?: Array<UserDelegatedAccess>
}
